name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['26.0', '25.3', '24.3']
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: '3.22.0'
      - name: Run tests project
        run: rebar3 test

  integration_test:
    name: docker container test with OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['25.3', '24.3']
    runs-on: 'ubuntu-22.04'
    env:
      OTP_RELEASE: ${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: '3.21.0'
      - run: ./ci/build_docker_image.sh
      - run: ./ci/start_demo_cluster.sh
      - run: ./ci/test_amoc_cluster.sh
      - run: ./ci/test_distribute_scenario.sh
      - run: ./ci/test_run_scenario.sh
      - run: ./ci/test_add_new_node.sh
      - run: ./ci/stop_demo_cluster.sh
